@echo off
echo Starting Docusaurus frontend server...
cd /d "C:\Users\hp\Desktop\book\ai-bases-book\ai-book"

echo Installing dependencies...
npm install

echo Starting frontend server...
npm run start